### DISCUSSION TITLE
Test for affected codebase subset instead of everything in the codebase

### DISCUSSION THREAD

**Discussion by yarnabrina** [alan-turing-institute/sktime#4453] [General]
As of now, all pull requests in `sktime` tests for each and every functionality. This is probably (actually quite certainly) safer, but it takes a LOT of time, especially since same tests run on multiple platforms. I've read in few issues that few tests are split across different platforms, but still it does take long.

For example, let's take an example: https://github.com/sktime/sktime/actions/runs/4615853258. The [PR](https://github.com/sktime/sktime/pull/4437) had no code changes, so certainly none of the configured workflows (except that of read the docs) have the scope of failing ever, except few very specific scenarios:

1. environment setup failure in GitHub actions
2. change of dependencies of any of `sktime` dependencies (like #4449)
3. (is there any more?)

I would like to think that these two are extreme rare scenarios and does not worth running tests for 2 hours and 35 minutes. Also, it'd never be in the scope of being fixed in same PR following the modular PR style followed here.

So, I was wondering if there is any reasons to not run tests selectively. For example, if I modify `SARIMAX` estimator, it should only tests on `SARIMAX`, and it should run those tests on every supported python version and every supported platform. But it should not run tests in `clustering` or `annotation`. Ideally, I'd prefer if not even other `forecasting` tests run unnecessarily, but that may be difficult to detect.

This is an idea for discussion. Please let me know if it's worth considering to add such test filtering, or if it has some other implications that I failed to notice.

**Comment by fkiraly** [comment]
This is an excellent idea, it was also discussed before in two "strains" of discussion.
The answer so far, it does not seem easy to identify the subset to be tested, even with a package that is dedicated specifically at testing only the diffs (`pytest-testmon`). The problem is the interaction with the test class framework which makes the usually sufficient criterion ("line touched") incorrect.

General discussion thread on how best to reduce test time:
https://github.com/sktime/sktime/issues/2890

Discussion on how to use `pytest-testmon` for `sktime`, @tarpas has even created a nice prototype!
https://github.com/sktime/sktime/issues/2530
context: `pytest-testmon` is a plugin for `pytest` which covers precisely this use case - testing only increments and not the entire code base!

@tarpas, in case you are still active and/or watching this, where did we end up getting stuck? anything we should be doing next, in your opinion?

**Reply by fkiraly** [reply]
> Please let me know if it's worth considering to add such test filtering, or if it has some other implications that I failed to notice.

I think it's quite high up on the wishlist of everyone, the main impediment being "no one has found a way to do it properly yet".

**Reply by tarpas** [reply]
> @tarpas, in case you are still active and/or watching this, where did we end up getting stuck? anything we should be doing next, in your opinion?

I'm still watching but not reacting much because I don't have a silver bullet for you :/. It's a hard problem. I'm not offering pytest-testmon and testmon.net for you yet because I don't consider our solution to be stable enough yet for a large project like yours. The time is near when I'll be able to but I can't offer an ETA.

I'll give some suggestions lower...

**Comment by fkiraly** [comment]
> (is there any more?)

other failure conditions for code that is not directly changed:

* direct dependency updates
* `sktime` internal dependencies, e.g., one estimator being a hard-coded component of another
* hard to spot side effects, e.g., a forgotten `clone`

**Comment by fkiraly** [comment]
There is also a very hacky thing core devs tend to do: if they *know* the test scope in some CI elements is superfluous, we cancel them manually and consider them as passed.

**Comment by yarnabrina** [comment]
I've zero experience with `pytest-testmon`, so apologise if if it's a better more feature complete solution. But what I have in mind is a simple filtering, at least by some extent to reduce times.

(What I am going to say below is what I have used quite a lot on Gitlab CI for my work related works. There should be Github Actions counterparts for achieving the same.)

1. Instead of a single `test-estimators` workflow, create multiple workflows, for example `test-forecast-estimators`, `test-annotator-estimators`, `test-classifier-estimators`, etc.
2. Instead of triggering these workflows on just creation of `pull_request` or on `push` to existing `pull_request`, add condition on change in `forecasting`, `annotation`, `classification` etc. folders.

The second point can be achieved quickly using [`paths` parameter](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request), if I'm following correctly.

For the first point, one can use `-k` flag extensively, which does support filtering by full test file path substring.

Admittedly, it still leads us to not go to very filtered specific tests, we are still at a higher level of forecasting vs classification etc. But hopefully it'd save some time.

**Reply by fkiraly** [reply]
hmmm, that could work!

How would you check the condition, "a forecaster has changed", precisely? That's the only point I don't quite see here.

**Reply by yarnabrina** [reply]
I'm thinking of something along these lines:

```yaml
name: test-forecasters
run-name: Test all forecasting codes
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "sktime/forecasting/**"
  push:
    branches:
      - main
    paths:
      - "sktime/forecasting/**"
defaults:
  run:
    shell: bash
jobs:
  forecast-tester:
    name: Test forecasters
    strategy:
      fail-fast: false  # to not fail all combinations if just one fail
      matrix:
        runner-platform:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
      max-parallel: 4  # at most 4 out of 15 will run simultaneously
    runs-on: ${{ matrix.runner-platform }}
    steps:
      - name: checkout commit
        uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          cache: pip  # pip cache folder will be used to save time
      - name: install sktime along with all dependencies
        run: python -m pip install -U .[all_extras,dev]  # -U will ensure latest packages, and will still use cache
      - name: run unit tests for forecasters on python ${{ matrix.python-version }} in runner ${{ matrix.runner-platform }}
        run: python -m pytest -k "forecast"  # example pattern
        # run: python -m pytest sktime/forecasting  # another possibility
      - name: upload coverage reports
        uses: codecov/codecov-action@v3
```

This is absolutely not tested, just edited one of my personal repository files.

> How would you check the condition, "a forecaster has changed", precisely?

Here lines 11 and 16 will evaluate to `True` if and only if some forecaster is changed. Admittedly, the bijection is assumed, I am not familiar enough to be sure.

And once again, just this will not ensure to just run `test_sarimax.py` if only change is in `sarimax.py`,  but at least it won't run all tests in non-forecasting folders.
