### DISCUSSION TITLE
Hierarchical forecasting with unequal (short and long) length of time series.

### DISCUSSION THREAD

**Discussion by ggjx22** [alan-turing-institute/sktime#6020] [Q&A]
Hello sktime Community,

I am currently in the midst of exploring the usage and end-to-end set up of Hierarchical Forecasting and I am met with the following obstacles which I will like to seek guidance here.

This is what I want to achieve:
- To have an end-to-end pipeline that implement Hierarchical Forecasting using a single and tuned global ensemble tree model.
- To forecast each and every time series at lowest node in the hierarchy by a certain forecast horizon regardless the length of the time series.
- To reconcile forecast at each level of the hierarchy.

The nature of my dataset:
- Hierarchy structure: Group companies -> country -> branch -> department -> product.
- forecast target: transactional values of product (all positives and negatives and mix of both).
- Project requirements are to forecast on product level and later on aggregate by sum up to different levels of the hierarchy and measure percentage error between forecast and actual.

Obstacles:
1. Some time series do not have at least 24 observations. They are as short as 12 observations.

Questions about my problem statement:
1. If my dataset suffer from lack of data from some time series, does that mean this approach is not suitable till I have enough data?
2. Aggregating target to a node higher can give me a collective time series with longer length, but are there still other approaches to my problem?

Questions about the code below:
1. If a Hierarchical dataset contains time series of different seasonality, does `TransformedTargetForecaster` applies the same `sp` parameter in `Deseasonalizer` to all time series?
2. Does the usage of `PluginParamsTransformer` solve this? And then again, there is still a need to `fit` the training data and manually inspect the value of `sp` via `.get_params()["sp"]`.

Below is the reproducible example:
```python
# imports
import pandas as pd
import numpy as np
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.base import ForecastingHorizon
from sklearn.ensemble import RandomForestRegressor
from sktime.pipeline import make_pipeline
from sktime.forecasting.compose import make_reduction, ForecastingPipeline, TransformedTargetForecaster
from sktime.transformations.series.detrend import Detrender, Deseasonalizer
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.summarize import WindowSummarizer
from sktime.transformations.series.date import DateTimeFeatures
from sktime.transformations.compose import TransformIf
from sktime.param_est.stationarity import StationarityADF
from sklearn.preprocessing import OrdinalEncoder
from sktime.transformations.series.adapt import PandasTransformAdaptor
from sktime.param_est.compose import ParamFitterPipeline
from sktime.param_est.seasonality import SeasonalityACF

RANDOM_STATE = 2

# create hierarchical dataset
data = _make_hierarchical(
    hierarchy_levels=(3, 4),
    max_timepoints=100,
    min_timepoints=12,
    all_positive=False,
    index_type="period",
    random_state=RANDOM_STATE,
)

# simulate exogenous variables out from hierarchy names, assuming they are useful
data['feature_1'] = data.index.get_level_values('h0')
data['feature_2'] = data.index.get_level_values('h1')

# create train and holdout dataset with last 12 observations
test = pd.DataFrame(columns=['c0'])

for name, group in data.groupby(level=['h0', 'h1']):
    test = pd.concat([test, group.tail(12)])
    
test.index = pd.MultiIndex.from_tuples(test.index, names=('h0', 'h1', 'time'))
train = data.drop(test.index)

# split X and y
X_train = train.drop(columns=['c0'])
y_train = train[['c0']]
X_test = test.drop(columns=['c0'])
y_test = test[['c0']]

# doing this because check raise TypeError: input should not have column of 'object' dtype
group_encoder = OrdinalEncoder()
group_encoder.fit(X_train)
train_encoding = group_encoder.transform(X_train)
X_train['feature_1_enc'] = train_encoding[:, 0]
X_train['feature_2_enc'] = train_encoding[:, 1]
X_train.drop(columns=['feature_1', 'feature_2'], inplace=True)

test_encoding = group_encoder.transform(X_test)
X_test['feature_1_enc'] = test_encoding[:, 0]
X_test['feature_2_enc'] = test_encoding[:, 1]
X_test.drop(columns=['feature_1', 'feature_2'], inplace=True)

# define forecast horizon
fh = ForecastingHorizon(np.arange(1, 12+1, 1), is_relative=True)

# create transformation & forecasting pipeline for target
kwargs = {
    "lag_feature": {
        "lag": [1],
        "mean": [[1, 3]],
        "std": [[1, 3]],
    }
}

tree_regressor = make_pipeline(RandomForestRegressor(random_state=RANDOM_STATE))

tree_forecaster = make_reduction(
    estimator=tree_regressor,
    window_length=None,
    transformers=[WindowSummarizer(**kwargs, n_jobs=-1, truncate='bfill')],
    pooling='global'
)

detrender = Detrender()
nan_remover = PandasTransformAdaptor(method='dropna')
deseasonalizer = Deseasonalizer(sp=12)

auto_difference = TransformIf(
    if_estimator=StationarityADF(),
    param='stationary',
    condition='==',
    condition_value=False,
    then_trafo=Differencer(),
    else_trafo=None
)

forecast_pipe = TransformedTargetForecaster(
    steps=[
        ('difference_if', auto_difference),
        ('remove_trend', detrender), # creates nan values
        ('remove_nan', nan_remover),
        ('remove_season', deseasonalizer),
        ('forecaster', tree_forecaster)
    ]
)

# define transformers to create exogenous features
date_features = DateTimeFeatures(ts_freq='M', keep_original_columns=True)

# create end to end pipeline
pipe = ForecastingPipeline(
    steps=[
        ('date_features', date_features),
        ('forecaster', forecast_pipe)
    ]
)

pipe.fit(y=y_train, X=X_train, fh=fh) # errors here
```

error:
```ValueError: x must have 2 complete cycles requires 24 observations. x only has 15 observation(s)```

package versions:
```
System:
    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\agpgago\data-science\forecast-wizard-test\venv\Scripts\python.exe](file:///C:/Users/agpgago/data-science/forecast-wizard-test/venv/Scripts/python.exe)
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 23.3.2
       sktime: 0.26.1
      sklearn: 1.4.1.post1
       skbase: 0.7.2
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.1.4
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.58.1
  statsmodels: 0.14.1
     pmdarima: 2.0.4
statsforecast: 1.7.3
      tsfresh: 0.20.2
      tslearn: 0.6.3
        torch: None
   tensorflow: 2.15.0
tensorflow_probability: None

```
