### ISSUE TITLE
extremely slow score/predict methods for sktime.classifier APIs 

### ISSUE THREAD

**Issue by nealgravindra** [alan-turing-institute/sktime#1039]
**Describe the bug**

Slow (several minutes, without completion) computation when trying to predict or score time-series classifiers with `sktime.classification` APIs. Issue is not resolved even if the label dtype is modified (to object, float, int, etc.) even though example seems to use str type for labels (see input [4] [here](https://www.sktime.org/en/latest/examples/02_classification_univariate.html)).

**To Reproduce**
See code snippet below, with simulated data. 

```python
import numpy as np
from sktime.utils.data_processing import from_2d_array_to_nested
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

# simulate data as sinusoid for 1000 samples, add white noise
t = np.linspace(0, 2*3.14, 2048)
x = np.repeat(np.sin(t).reshape(-1, 1), 1000, axis=1).T
x += np.random.uniform(0, 1, size=x.shape)

# convert to sktime data rep
X_train = from_2d_array_to_nested(x)

# init and fit model
clf = KNeighborsTimeSeriesClassifier()
dummy_binary = np.array(np.random.choice([0, 1], X_train.shape[0]), dtype=str)
clf.fit(X_train, dummy_binary)

# eval
clf.score(X_train, dummy_binary) # SLOW, does not complete computation
# clf.predict(X_train) # same problem as above
```

**Expected behavior**
The classifier fits in ms, and I expect the scoring/predict methods to be fast as well.

**Additional context**
Trying to do a multi-class classification problem with 1D time-series and ran into this bug while trying to get baselines using several classifiers from sktime. I thought it was an sklearn issue (perhaps related to [issue#10802](https://github.com/scikit-learn/scikit-learn/issues/10802)); however, when interrupted, the `clf.score(...)` method is stuck inside some `sktime` script after calling `clf.predict`, e.g., see tiny error snippets below for the cBOSS classifier:
```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-258-f0a73361dd80> in <module>
     15 dummy_binary = np.array(np.random.choice([0, 1], X_train.shape[0]), dtype=str)
     16 clf.fit(X_train, dummy_binary)
---> 17 clf.score(X_train, dummy_binary)
     18 # clf.predict(X_train) # same problem as above

~/.local/lib/python3.8/site-packages/sktime/classification/dictionary_based/_cboss.py in predict_proba(self, X)
    254 
    255         for n, clf in enumerate(self.classifiers):
--> 256             preds = clf.predict(X)
    257             for i in range(0, X.shape[0]):
    258                 sums[i, self.class_dictionary[preds[i]]] += self.weights[n]
```

**Versions**
```
System:
    python: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable: /usr/bin/python3
   machine: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29

Python dependencies:
          pip: 20.0.2
   setuptools: 45.2.0
      sklearn: 0.24.2
       sktime: 0.6.1
  statsmodels: 0.12.2
        numpy: 1.20.3
        scipy: 1.4.1
       Cython: 0.29.23
       pandas: 1.2.4
   matplotlib: 3.2.1
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: None
      tsfresh: None
```

</details>
