### ISSUE TITLE
[BUG] Prophet does not work with integer indices

### ISSUE THREAD

**Issue by paxcema** [alan-turing-institute/sktime#2564]
Update by @fkiraly:

after some discussion, I think this is the "actual" bug, i.e., that integer index does not work with `Prophet`:

Hm, I think it might be a bug, because this does not work:

```python
import numpy as np
import pandas as pd
from sktime.forecasting.fbprophet import Prophet

y = pd.DataFrame(np.arange(1, 100), columns=['0'])

f = Prophet()
f.fit(y)
predictions = f.predict(fh=[1])
```

I think it should, instead of erroring out.
The error message says that index needs to be sth or integer index, but it *is* integer index!

---

**Describe the bug**

Trying a flow similar (but not exactly the same) to the one in the Prophet getting started guide, I run into an issue when making the call to predict.

**To Reproduce**

```python
import numpy as np
import pandas as pd
from sktime.forecasting.fbprophet import Prophet

y = pd.DataFrame(np.arange(1, 100), columns=['0'])
y.index = y.index.astype('datetime64[ns]')
f = Prophet()
f.fit(y)
predictions = f.predict(fh=[1])
```

**Expected behavior**

Predictions should be made and stored in the `predictions` variable.

**Additional context**

**Versions**
<details>

```
System:
    python: 3.8.6 (default, Nov 20 2020, 18:29:40)  [Clang 12.0.0 (clang-1200.0.32.27)]
executable: /Users/Pato/env/bin/python3.8
   machine: macOS-10.16-x86_64-i386-64bit
Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.2
      sklearn: 1.0.2
       sktime: 0.11.2
  statsmodels: 0.12.1
        numpy: 1.21.5
        scipy: 1.4.1
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 0.17.0
        numba: None
     pmdarima: 1.8.0
      tsfresh: None
```

</details>
