### ISSUE TITLE
[BUG] ForecastingGridSearchCV with a ReducedRegressionForecaster does not display the right number of candidates

### ISSUE THREAD

**Issue by ngupta23** [alan-turing-institute/sktime#585]
**Describe the bug**

1. Using the `ForecastingGridSearchCV` with a `ReducedRegressionForecaster` does not display the right number of candidates
2. Eventually, the best_parameters_ for the underlying sklearn regressor are not accessible

**To Reproduce**
```python
y = load_airline()
y_train, y_test = temporal_train_test_split(y, test_size=36)

regressor_param_grid = {"n_estimators": [100, 200, 300]}
forecaster_param_grid = {
    "deseasonalise__sp": [6, 12, 24],
    "detrend__forecaster__degree": [1, 2],
    "forecaster__window_length": [10, 12, 15, 20, 25]
}

# create a tunnable regressor with GridSearchCV
regressor = GridSearchCV(RandomForestRegressor(random_state=42), param_grid=regressor_param_grid)
forecaster = TransformedTargetForecaster(
    [
        ("deseasonalise", Deseasonalizer(model="multiplicative")),  
        ("detrend", Detrender(forecaster=PolynomialTrendForecaster())),
        ("forecaster", ReducedRegressionForecaster(regressor=regressor, strategy="recursive")) 
    ]
)

cv = SlidingWindowSplitter(
    initial_window=int(len(y_train) * 0.5),
    start_with_window=True,
    window_length=36
)
gscv = ForecastingGridSearchCV(forecaster, cv=cv, param_grid=forecaster_param_grid, verbose=True)
%time gscv.fit(y_train)
```

```terminal
Fitting 72 folds for each of 30 candidates, totalling 2160 fits
Wall time: 3min 1s
```

**Expected behavior**

1. I was expecting to see 30 * 3 = 90 candidates. I think the count is ignoring the underlying parameters in sklearn's GridSearchCV.
2. Secondly, I tried to access the underlying random forest regressor best parameters but could not, even though the regressor itself could be accessed. Not sure if this is a bug.

```python
print(f"Best Params: {gscv.best_params_}")
print(f"Detrender Degree: {gscv.forecaster.named_steps['detrend'].forecaster.degree}")
print(f"Internal Regressor: {gscv.forecaster.named_steps['forecaster'].regressor}")  # Unable to print best_params_
```

```terminal
Best Params: {'deseasonalise__sp': 6, 'detrend__forecaster__degree': 1, 'forecaster__window_length': 25}
Detrender Degree: 1
Internal Regressor: GridSearchCV(estimator=RandomForestRegressor(random_state=42),
             param_grid={'n_estimators': [100, 200, 300]})
```

**Versions**
```
System:
    python: 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\sktime_dev\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.3.3
   setuptools: 51.0.0.post20201207
      sklearn: 0.24.0
       sktime: 0.5.1
  statsmodels: 0.12.1
        numpy: 1.19.4
        scipy: 1.5.4
       Cython: 0.29.17
       pandas: 1.1.5
   matplotlib: 3.3.3
       joblib: 1.0.0
        numba: 0.52.0
     pmdarima: 1.8.0
      tsfresh: 0.17.0
```
