### ISSUE TITLE
[BUG] KeyError when forecasting using non-unit frequencies

### ISSUE THREAD

**Issue by ckastner** [alan-turing-institute/sktime#868]
**Describe the bug**

I happen to have a time series with a frequency of 30 minutes. Attempting to use this during forecasting triggers a `KeyError` in pandas.

This is because the datetime module assumes that the frequency is always 1 of some unit, ie `(1, freq)`:

https://github.com/alan-turing-institute/sktime/blob/4be4866ac50f0c6ce422716d529e95bfbf25411d/sktime/utils/datetime.py#L41-L44

However, the frequency in my case in `30T`, which is called as `pd.Timedelta(1, "30T")`, which triggers the `KeyError`. Instead, The expected call is `pd.Timedelta(30, "T")`.

The `freqstr` returned by pandas seems to be parsed into a compact one-letter representation. At least, when I manually specified a frequency of `30mins`, reading the frequency returned `30T`. If this is generally true, then a `freqstr` of length > 1 implies that `freqstr[:-1]` hold the number of actual units.

However, a cleaner solution might be to fix this in `_get_freq`:
https://github.com/alan-turing-institute/sktime/blob/4be4866ac50f0c6ce422716d529e95bfbf25411d/sktime/utils/datetime.py#L53-L58

**To Reproduce**

```python
import numpy as np
import pandas as pd

from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.ets import AutoETS

s = pd.Series(
    np.random.rand(100),
    index=pd.date_range('20130101 09:00:00', freq='30T', periods=100)
)

y_train = s[:80]
y_test = s[80:]
fh = ForecastingHorizon(y_test.index, is_relative=False)
forecaster = AutoETS(auto=True, sp=5, n_jobs=-1)
forecaster.fit(y_train)

# KeyError
y_pred = forecaster.predict(fh)
```

**Versions**

```
System:
    python: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
executable: /home/christian/TUWien/Energy-efficient Distributed Systems/venv/bin/python3
   machine: Linux-5.10.0-0.bpo.5-amd64-x86_64-with-debian-10.9

Python dependencies:
          pip: 18.1
   setuptools: 40.8.0
      sklearn: 0.24.2
       sktime: 0.6.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.6.3
       Cython: 0.29.23
       pandas: 1.2.4
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: None
     pmdarima: 1.8.2
      tsfresh: None
```
