### ISSUE TITLE
[BUG] Prophet adapter fails to clone after setting parameters

### ISSUE THREAD

**Issue by Yard1** [alan-turing-institute/sktime#910]
**Describe the bug**

Using sklearn's `clone` on `Prophet` after either `seasonality_prior_scale`, `changepoint_prior_scale` or `holidays_prior_scale` were set with a non-float value through `set_params` will raise a `RuntimeError` during cloning. This is due to the `float` conversion happening in `__init__`, which is against what sklearn expects during cloning - it expects that all of the values passed as arguments to `__init__` will not be modified in any way when being set as object attributes.

**To Reproduce**

```python
from sktime.forecasting.fbprophet import Prophet
from sklearn.base import clone
model = Prophet()
model.set_params(changepoint_prior_scale=1)
clone(model)
```

This will raise a sklearn `RuntimeError`.

**Expected behavior**

No exception is raised.

**Additional context**

**Versions**
<details>

```
System:
    python: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable: /home/baum/anaconda3/bin/python
   machine: Linux-5.11.0-7614-generic-x86_64-with-glibc2.10

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.23.2
       sktime: 0.5.3
  statsmodels: 0.12.2
        numpy: 1.20.1
        scipy: 1.6.1
       Cython: 0.29.17
       pandas: 1.2.3
   matplotlib: 3.4.1
       joblib: 1.0.1
        numba: 0.51.2
     pmdarima: 1.8.0
      tsfresh: None
```
</details>
